### ISSUE TITLE
Dell UltraSharp 2209WAf: DDC communication failed

### ISSUE THREAD

**Issue by w8jcik** [rockowitz/ddcutil#424]
I have three displays connected directly to an Intel GPU.

Two displays work fine with `ddcutil`  but the third Dell 2209WAf shows _DDC communication failed_.

Failing Dell 2209WAf is capable of DDC (display, wires), based on a fact that it's DDC works after reboot to Windows.

## Debug commands

Output from `ddcutil interrogate --verbose`
[DELL-2209WAf-interrogate-report.log](https://github.com/rockowitz/ddcutil/files/15467210/DELL-2209WAf-interrogate-report.log)  
(intentionally disconnected other displays for the report).

Looking at some past issues I also tried calling

```bash
ddcutil detect --ddc  # no extra output
ddcutil detect --f4  # all strategies failed
ddcutil detect --maxtries 15,15,15 --sleep-multiplier=2 --stats   # no change from ddcutil detect --stats
# tried different multipliers 1.1, 1.2, 1.3, 1.4, 1.5, 2, 5, 10 ... 99
```

Display does not get a number, so calling by a bus number

```
ddcutil --bus 3 setvcp 10 50 --noverify
```

```
DDC communication failed for monitor on bus /dev/i2c-3
```

## GPU

```bash
inxi -G
```

```
Graphics:
  Device-1: Intel Iris Pro Graphics 580 driver: i915 v: kernel
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 resolution: 2560x1440~60Hz
  API: EGL v: 1.5 drivers: iris,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.5-1ubuntu1
    renderer: Mesa Intel Iris Pro Graphics 580 (SKL GT4)
  API: Vulkan v: 1.3.275 drivers: N/A surfaces: xcb,xlib,wayland
```

`i2c-dev` is built into kernel, the default Ubuntu 24.04 LTS kernel.

## Versions of `ddcutil`

I tried `ddcutil@1.4.1` shipped with Ubuntu 24.04 LTS, as well as manually built `1.4.5` and `2.1.5-dev`.

## Other platforms

Brightness control of all three displays works in Windows, so it is not related to wires or wrong settings of the display. The application I tried is called https://github.com/emoacht/Monitorian. Although I think that Monitorian does nothing special, just Windows API does DDC out of the box.

## Past issues

I found this issue https://unix.stackexchange.com/questions/546000/adjust-backlight-via-ddc

>  I am the developer of [ddcutil](http://www.ddcutil.com/).
> 
> It looks like you have a monitor with a marginal I2C implementation. The Nvidia options are forcing the driver to use the lowest bus speed defined in the I2C spec, 100 kbps. Unfortunately, there's no way to tell the driver to use an even lower bus speed.

The OP solved it by passing parameters to Nvidia kernel module, but this is an Intel GPU.
